name: json_schema_matcher
description: A Dart library for JSON schema validation using native testing framework matchers with strongly-typed validators and detailed error messages.
version: 1.0.3
repository: https://github.com/alessandro-amos/json_schema_matcher

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  test: ^1.24.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0