name: json_schema_matcher
description: A Dart library for JSON schema validation using native testing framework matchers with strongly-typed validators and detailed error messages.
version: 1.0.3
repository: https://github.com/alessandro-amos/json_schema_matcher

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  test: ">=1.24.0 <2.0.0"

dev_dependencies:
  lints: ">=3.0.0 <5.0.0"