name: Dart Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, "3.8.0", "3.6.0", "3.0.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart ${{ matrix.sdk }}
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings

      - name: Run tests (root)
        run: dart test